### ISSUE TITLE
xfce4-panel-profiles is missing from the image

### ISSUE THREAD

**Issue by ali1234** [ublue-os/vauxite#5] opened 2023-02-07 22:35 UTC
This is a fairly important part of Xfce that people will expect to be available after installing. It allows the user to quickly switch between some pre-made panel layouts mimicking various other desktops as well as load up their own personal custom configuration files. As such it is one of the first thing people use on a fresh install.

**Comment by hyperreal64** [comment] 2023-02-07 23:37
> This is a fairly important part of Xfce that people will expect to be available after installing. It allows the user to quickly switch between some pre-made panel layouts mimicking various other desktops as well as load up their own personal custom configuration files. As such it is one of the first thing people use on a fresh install.

Thanks for bringing this to our attention. A fix for this will be merged into the main branch shortly. You should be able to update your system with the change in 1-2 hours, as the resulting image will be pushed to the container registry after it's built.

I agree that this is an important part of Xfce and should be available on fresh installs. The issue is from upstream, the comps-sync.py script pulls in packages for each comps group. In the case of Xfce, the packages are then saved in a file called xfce-desktop-pkgs.yaml. Apparently the xfce-desktop comps group does not include xfce4-panel-profiles, which it should. An ideal fix would be for the upstream comps to include xfce4-panel-profiles, and I will submit a pull request for that. In the meantime, we can add the package to the main treefile that is used to build the image.

**Closed as completed** 2023-02-07 23:47 UTC
